{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gapminder
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gapminder_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gapminder/gapminder_{{ version }}.tar.gz
  sha256: edd138576fcff02ac41f9580dbd9713f3e98a9bd32039decd098078b421a351f

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-tibble
  run:
    - r-base
    - r-tibble

test:
  commands:
    - $R -e "library('gapminder')"           # [not win]
    - "\"%R%\" -e \"library('gapminder')\""  # [win]

about:
  home: https://github.com/jennybc/gapminder, http://www.gapminder.org/data/, https://doi.org/10.5281/zenodo.594018
  license: CC0-1.0
  license_file: LICENSE
  summary: An excerpt of the data available at Gapminder.org. For each of 142 countries, the package provides values for life expectancy, GDP per capita, and population, every five years, from 1952 to 2007.

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
