appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: iHVgRjmnHMC0A6Z6JD2Qch+qkMmWeDPg5VBHyFmQ7Qa605d0PR+ny38M/Sfkyf9w4QyUXNOrCrGIm1K9aO9mPO+9zD4SYwrbuU3z5sgqDjHfWC5UZI7dz6OngECI1apMzKS+1CjOs2fQL3nXYwQttXTzGHNRhz4GvHsZIUW2l0K8ctBlMRST2jdruhI47rBBKJJRRgkA/0uYlo2J3ypHfFu0+64pRmwhsWrH+kQo4XydrEwkSgFw6RVwhugWBg9c1ym+2XAt/snSXxFD3Se958DYroNl6pzQ2KzYhLmbex02kyck2r6Nd48mA8lCHEOAs2Af5Rgb57X1HLO1d2/6p8hUC3TBbnuybg4yUOFXC8lYG/9+mhUcRCQQo7Nm8lsFlzLFnK9yy+5Cb/LZpDRMgaSCZpjdRQ6974wUgQ8VTjGIzmyl16xixfVD0x361urtdnqbNxL+wYvGfd3iv0Ic+NsFgTja7RgMxQ6yBT9iCjHPqnxqG6I8egyvybvHW8X3RksqRuWBS5nbtOPxvE5VYaOyK/OSNtBEh/OSX5F/+0J/BYrP5CCnA2Y2Gf5eHeLfwby5v60YziekrKNEqCCkVOC8XLv1z9URYlys5aum+vsDCzeUqo7BtrTytiIFOXGaSay8aNQcMCfCrmf6ubNEYUnqaK5Vp/cqdJL15z0KyDM=}
bot:
  automerge: true
